# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Scarf" do
pod 'AFNetworking', '~> 2.0.3'
pod 'ReactiveCocoa', '~> 2.1.8'
#pod 'AFNetworking-RACExtensions', '~> 0.1.2'
pod 'VENSnowOverlayView', '~> 0.1.1'
pod 'EAIntroView', '~> 2.2.0'
end

target "ScarfTests" do
pod 'Kiwi/XCTest'
pod 'OHHTTPStubs', '~> 3.0.4'
pod 'OCMock', '~> 2.2.2'
end

